name: CraftHub
main: cz.wake.hub.Main
version: 1.1
author: MrWakeCZ
depend: [Multiverse-Core]

commands:
  sendplayer:
    description: Odesilani hracu do lobby
  skip:
    description: Primi teleport do lobby
